name: On Demand Search for Email

on:
  workflow_dispatch:

jobs:
  search_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build gosearch
        run: go build -o gosearch .
      - name: Run gosearch for email
        run: ./gosearch -u andreileonsalas@gmail.com
