name: On Demand Search for Email

on:
  workflow_dispatch:
    inputs:
      email:
        description: 'Email a buscar'
        required: true
        type: string
      breach_api_key:
        description: 'API Key de BreachDirectory (opcional)'
        required: false
        type: string

jobs:
  search_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build gosearch
        run: go build -o gosearch .
      - name: Run gosearch for email (más preciso)
        run: |
          if [ -z "${{ github.event.inputs.breach_api_key }}" ]; then
            ./gosearch -u "${{ github.event.inputs.email }}" --no-false-positives
          else
            ./gosearch -u "${{ github.event.inputs.email }}" -b "${{ github.event.inputs.breach_api_key }}" --no-false-positives
          fi
